apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qa9jevu0a-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qa9jevu0a-dotnet-basic-gitops